# Numpy Practices

## Imaging Editing

### Counter-color 

In [1]:
import numpy as np

In [2]:
from PIL import Image

In [8]:
a = np.array(Image.open('./Files/fcity.jpg')) #Image.open() to read image

In [9]:
print(a.shape, a.dtype)

(441, 634, 3) uint8


In [10]:
print(a[:2,:2,:]) #3D array of an image

[[[ 53 130 198]
  [ 53 130 198]]

 [[ 53 130 198]
  [ 53 130 198]]]


In [37]:
b = [255,255,255] - a #Auto-Match dimension to Calculate
print(b[:4,:4,:]) #the counter-color of every pixel
print(b.dtype) #After calculation, new array is int64

[[[202 125  57]
  [202 125  57]
  [202 125  57]
  [202 125  57]]

 [[202 125  57]
  [202 125  57]
  [202 125  57]
  [202 125  57]]

 [[202 124  58]
  [202 124  58]
  [202 124  58]
  [202 124  58]]

 [[202 124  58]
  [202 124  58]
  [202 124  58]
  [202 124  58]]]
int64


In [15]:
im = Image.fromarray(b.astype('uint8')) #returns a new unit8 array and save
print(b.dtype) #.astype NOT modify

In [16]:
im.save('./Files/fcity2.jpg') 

### Grey Scale Editing

In [29]:
import numpy as np
from PIL import Image

In [30]:
g = np.array(Image.open('./Files/fcity.jpg').convert('L'))
#.Image.open().convert('L') convert [R,G,B] to (greyscale)
#3D-->2D 

In [36]:
print(g.shape, g.dtype)
print(g[:4,:4]) #grey scale is 2D 

(441, 634) uint8
[[114 114 114 114]
 [114 114 114 114]
 [115 115 115 115]
 [115 115 115 115]]


In [47]:
gim = Image.fromarray(g.astype('uint8'))

In [48]:
gim.save('Files/fcity3.jpg')

![title](./Files/fcity3.jpg)

#### 3 Examples of Other Modification

In [52]:
#1. Film-like grey
gc =  255 - g 

In [ ]:
#2. Lighter grey
gc = (100/255)*g + 150 

In [ ]:
#3. Darker grey
gc = 255 * (g/255)**2 

In [53]:
gcim = Image.fromarray(gc.astype('uint8'))

In [60]:
gcim.save('./Files/fcity4.jpg')

some problem with this one, but it should have looked like Film 
<br>![title](./Files/fcity4.jpg)