---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

<br> 
# The Python Programming Language: Numerical Python (NumPy)

In [2]:
import numpy as np

<br> 
## Creating Arrays

Create a list and convert it to a numpy array

In [140]:
mylist_or_tuple = (([1, 2, 3]))
x = np.array(mylist_or_tuple) #convert to []/[[]] anyway
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [131]:
y = np.array([4, 5, 6],'f')
y

array([4., 5., 6.], dtype=float32)

<br>
Pass in a list of lists to create a multidimensional array.

In [123]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br> 
`ndim` return dimension<br>
`shape` returns structure<br>
`size` returns element count(m*n)<br>
`itemsize` returns bit size per element<br>
`dtype` returns data type of element

In [7]:
m.ndim #1D, 2D or 3D

2

In [124]:
m.shape # m, n

(2, 3)

In [125]:
m.size # m * n

6

In [126]:
m.itemsize

8

In [127]:
m.dtype

dtype('int64')

<br> 
**Heterogeneous Array** is allowed, but should **avoid** 

In [130]:
h = np.array([[0,1,2,3],[9,8],'hello'])
print(h)
print(h.dtype)
print(h.shape)
print(h.size)
print(h.itemsize)


[list([0, 1, 2, 3]) list([9, 8]) 'hello']
object
(3,)
3
8


<br>`arange` returns evenly spaced values within a given interval. #(Arrage)Range

In [163]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>`reshape` returns an array with the same data with a new shape.

In [165]:
print(n.reshape(3, 5)) # reshape array to be 3x5 
n

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>`resize` changes the shape and size of array in-place.

In [166]:
n.resize(3, 5) #IN-PLACE modify
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br> 
`flatten` returns reduced-dimension 

In [167]:
n.flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>`linspace(start,end,size,[incl_end])` returns evenly spaced numbers over a specified interval.

In [157]:
o = np.linspace(0, 4, 9, True) # return 9 evenly spaced values from 0 to 4
print(o.dtype)           # FLOAT is default dtype for creation 
o                        # (4-0)/(9-1)=5    

float64


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>`ones()` returns a new array of given shape and type, filled with ones.<br>
`ones_like()` returns a new array of the shape and type of input array, filled with ones.

In [150]:
np.ones((3, 2)) #create a new ndarray [d]*m*n

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [152]:
lk = np.random.randint(0,10,(3, 2))
np.ones_like(lk)

array([[1, 1],
       [1, 1],
       [1, 1]])

<br>`zeros()`, `zeros_like()` returns a new array of given shape and type, filled with zeros.

In [26]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br> 
`full_like(a,val)`returns an array of shape a filled with val

In [154]:
np.full_like(lk,7)

array([[7, 7],
       [7, 7],
       [7, 7]])

<br> 
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [31]:
print(np.eye(3)) #one parameter is ok
print(np.eye(3) == np.eye(3,3)) #1-to-1 compare

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


<br>`diag` extracts a diagonal or constructs a diagonal array.

In [34]:
print(y)
np.diag(y) #from 1D array 

[4 5 6]


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>Create an array using repeating list (or see `np.tile`)

In [3]:
np.array([1, 2, 3] * 3) #[a,b,c,a,b,c]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br> 
Repeat elements of an array using `repeat`.

In [4]:
np.repeat([1, 2, 3], 3) # [a,a,b,b,c,c]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br> 
#### Combining Arrays

In [7]:
p = np.ones([2, 3], int) #,int specify dtype to create
p

array([[1, 1, 1],
       [1, 1, 1]])

<br> 
Use `vstack` or `concatenate`to stack arrays in sequence vertically (row wise).

In [8]:
np.vstack([p, 2*p]) #Left to right (looks top down)

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [161]:
np.concatenate([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br> 
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [9]:
np.hstack([p, 2*p]) #extend every row

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br> 
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [95]:
print(x,type(x), y,type(y))
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

NameError: name 'x' is not defined

In [19]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [20]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br> Use **> < = <= == !=** to compare every element and generate boolean array

<br> 
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [21]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [22]:
z = np.array([y, y**2])
print(z)
print(len(z)) # number of rows of array

[[ 4  5  6]
 [16 25 36]]
2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [32]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br> 
The shape of array `z` is `(2,3)` before transposing.

In [24]:
z.shape

(2, 3)

<br> 
Use `.T` to get the transpose.

In [25]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [26]:
z.T.shape

(3, 2)

<br> 
Use `.dtype` to see the data type of the elements in the array.

In [27]:
z.dtype

dtype('int64')

<br> 
Use `.astype` to cast to a specific type.

In [168]:
z = z.astype('f') #keep as ndarray
print(z, z.dtype)

[[ 4.  5.  6.]
 [16. 25. 36.]] float32


<br> 
`tolist` returns a python list

In [169]:
z.tolist()

[[4.0, 5.0, 6.0], [16.0, 25.0, 36.0]]

<br> 
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [47]:
a = np.arange(24)
a.resize((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
a.sum() == np.sum(a)

True

In [74]:
a.max() == np.max(a)

True

In [96]:
np.maximum(a, b, c) #returns an array of the largest element of each compare 

NameError: name 'b' is not defined

In [72]:
a.mean() == np.mean(a)

True

In [75]:
np.abs(a) 

AttributeError: 'numpy.ndarray' object has no attribute 'abs'

In [80]:
np.sqrt(a) == a ** 0.5

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [76]:
np.std(a) == a.std()

True

In [79]:
np.square(a) == a**2


array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [87]:
np.log(a) # natural log
np.log10(a) 
np.log2(a) 

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log10
  
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log2
  This is separate from the ipykernel package so we can avoid doing imports until


array([[[      -inf, 0.        , 1.        , 1.5849625 ],
        [2.        , 2.32192809, 2.5849625 , 2.80735492],
        [3.        , 3.169925  , 3.32192809, 3.45943162]],

       [[3.5849625 , 3.70043972, 3.80735492, 3.9068906 ],
        [4.        , 4.08746284, 4.169925  , 4.24792751],
        [4.32192809, 4.39231742, 4.45943162, 4.52356196]]])

In [94]:
np.exp(a) # e^x



array([[[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]],

       [[1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
        [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
        [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09]]])

In [91]:
print(np.ceil(a), '\n'*2, np.floor(a))

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]] 

 [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]


In [ ]:
np.rint() #round to int
np.modf() #return int and decimal parts as 2 arrays
np.sign() #return 1(+), 0(0), -1(-)



<br> 
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [45]:
a.argmax() #as a 1-D array

3

In [46]:
a.argmin()

0

<br> 
## Indexing / Slicing

<br> 
**General Slicing: a[D1,D2,..,Dn]**<br> 

a [ [start]:[end]:[step], [start]:[end]:[step], ... ]

In [2]:
import numpy as np

In [25]:
s = np.arange(24).reshape((2,3,4)) #resize does not work here
s

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [7]:
print(s[1,2,3])
print(s[-1,-2,-3])

23
17


<br> 
Use `:` to indicate a range. `array[start:stop:step]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [10]:
s[:,1,-3] 

array([ 5, 17])

In [11]:
s[:, 1:3, :]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
s[:, :, ::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

### Slicing v.s. Indexing<br> 
**Slicing** returns a segment of array, keeping the dimension<br>
**Index** select element and orgnize into a list

In [37]:
#Slice/Select of the same target
print('original array is'),print(s,'\n')
print('Slice D1,D2,D3:'),print(s[:1,:1,:1],'\n')
print('Slice D1,D2, Select D3:'),print(s[:1,:1,0],'\n')
print('Slice D1, Select D2,D3:'),print(s[:1,0,0],'\n')
print('Select D1,D2,D3:'),print(s[0,0,0])

original array is
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

Slice D1,D2,D3:
[[[0]]] 

Slice D1,D2, Select D3:
[[0]] 

Slice D1, Select D2,D3:
[0] 

Select D1,D2,D3:
0


(None, None)

In [92]:
#Difference between Numpy Arra
ls = [row for row in r ]
print('List of Numpy array is '+ str(ls))
ls = [list(row) for row in r ]
print('Python list is'+ str(ls) ) 
print('List slicing [3][3:6]:'+str(ls[3][3:6]))

List of Numpy array is [array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11]), array([12, 13, 14, 15, 16, 17]), array([18, 19, 20, 21, 22, 23]), array([24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35])]
Python list is[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35]]
List slicing [3][3:6]:[21, 22, 23]


<br> 
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [41]:
r = np.arange(0,36).reshape(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [101]:
print('r:'+ str(r))
r[r > 30] # "SELECT" into a 1D array

r:[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [102]:
r[r > 30] = 30 # "Replace"
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br> 
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [103]:
r2 = r[:3,:3] #r2 points to [:3,:3] of r
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br> 
Set this slice's values to zero ([:] selects the entire array)

In [104]:
r2[:] = 0 # r[:3,:3] is now 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br> 
`r` has also been changed!

In [107]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br> 
To avoid this, use `r.copy` or `astype()` to create a copy that will not affect the original array

In [109]:
r_copy = r.copy()
r_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Now when r_copy is modified, r will not be changed.

In [110]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


<br> 
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [111]:
test = np.random.randint(0, 10, (4,3)) #random
test

array([[3, 5, 8],
       [6, 9, 9],
       [8, 0, 8],
       [9, 7, 9]])

<br>
Iterate by row:

In [113]:
for row in test:
    print(row)
    print(type(row))

[3 5 8]
<class 'numpy.ndarray'>
[6 9 9]
<class 'numpy.ndarray'>
[8 0 8]
<class 'numpy.ndarray'>
[9 7 9]
<class 'numpy.ndarray'>


<br>
Iterate by index:

In [114]:
for i in range(len(test)):
    print(test[i])

[3 5 8]
[6 9 9]
[8 0 8]
[9 7 9]


<br>
Iterate by row and index:

In [115]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [3 5 8]
row 1 is [6 9 9]
row 2 is [8 0 8]
row 3 is [9 7 9]


<br> 
Use `zip` to iterate over multiple iterables.

In [116]:
test2 = test**2
test2

array([[ 9, 25, 64],
       [36, 81, 81],
       [64,  0, 64],
       [81, 49, 81]])

In [117]:
for i, j in zip(test, test2): #0,0-->1,1-->2,2-->3,3
    print(i,'+',j,'=',i+j)    #also works elsewhere

[3 5 8] + [ 9 25 64] = [12 30 72]
[6 9 9] + [36 81 81] = [42 90 90]
[8 0 8] + [64  0 64] = [72  0 72]
[9 7 9] + [81 49 81] = [90 56 90]


In [118]:
trial1 = [1,2,3] 
trial2 = [4,5,6]
for i,j in zip(trial1,trial2):
    print(i,'+',j,'=',i+j)

1 + 4 = 5
2 + 5 = 7
3 + 6 = 9


# Statistical Functions in NumPy

In [1]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

<br> 
np.`sum`(a, axis=None)<br>


In [4]:
np.sum(a) #axis = None --add entire array

105

In [14]:
np.sum(a, 0) # axis=0 --sum between elements

array([15, 18, 21, 24, 27])

In [10]:
np.sum(a, 1) #axis = 1 --sum for each 1st-D element

array([10, 35, 60])

<br> 
np.`mean`(a, axis=None)<br>


In [12]:
np.mean(a)

7.0

In [11]:
np.mean(a, 1)

array([ 2.,  7., 12.])

<br> 
np.`average`(a, axis=None, weights=None)<br>


In [16]:
np.average(a, axis=0, weights=[10,5,1])#assign weights in order

array([2.1875, 3.1875, 4.1875, 5.1875, 6.1875])

<br> 
np.`std`(a, axis=None)<br>


<br> 
np.`var`(a, axis=None)<br>


<br> 
np.`min`(a, axis=None)<br>
<br> 
np.`max`(a, axis=None)<br>

In [19]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
np.min(a,0)

array([0, 1, 2, 3, 4])

<br> 
np.`argmin`(a, axis=None)<br>
<br> 
np.`argmax`(a, axis=None)<br>

In [23]:
np.argmin(a,0) #Flatten by 1D

array([0, 0, 0, 0, 0])

In [24]:
np.argmax(a,0) #Flatten by 1D

array([2, 2, 2, 2, 2])

<br> 
np.`unravel_index`(index, shape)<br>


In [32]:
np.argmin(a)

0

In [34]:
np.unravel_index(np.argmin(a),a.shape)

(0, 0)

<br> 
np.`median`(a, axis=None)<br>

In [35]:
np.median(a, 1) #return float

array([ 2.,  7., 12.])

<br> 
np.`ptp`(a, axis=None)<br>


In [37]:
np.ptp(a,1) #=(max - min) for every axis

array([4, 4, 4])

## Gradient Calculation 

In [ ]:
import numpy as np

<br> 
np.`gradient`(f, axis=None)<br>

In [39]:
a = np.random.randint(0, 20, (5))
a

array([14, 12,  2,  0,  4])

In [40]:
np.gradient(a)

array([-2., -6., -6.,  1.,  4.])

In [41]:
b = np.random.randint(0, 20, (3,5))
b

array([[18, 13,  1, 14, 10],
       [11, 17,  7, 10, 19],
       [ 6,  7, 18, 17,  9]])

In [42]:
np.gradient(b) #return 2 directions for 2D array
                #1. Row-Column 2.Row-Row

[array([[ -7. ,   4. ,   6. ,  -4. ,   9. ],
        [ -6. ,  -3. ,   8.5,   1.5,  -0.5],
        [ -5. , -10. ,  11. ,   7. , -10. ]]),
 array([[-5. , -8.5,  0.5,  4.5, -4. ],
        [ 6. , -2. , -3.5,  6. ,  9. ],
        [ 1. ,  6. ,  5. , -4.5, -8. ]])]

# Random Functions in Numpy

In [1]:
import numpy as np

np.random.`seed()` <br>
<br> *Select the seed (optional)*

In [18]:
np.random.seed(10) #same outcome for same seed

np.random.`rand`(d0,d1,...dn)<br>
<br> *Create float in [0,1)*<br>

In [6]:
a = np.random.rand(3, 4, 5)
a

array([[[0.97304539, 0.34460644, 0.82122149, 0.30988057, 0.3706934 ],
        [0.86370825, 0.03065025, 0.84316238, 0.86598143, 0.23480537],
        [0.89306687, 0.10774236, 0.86817097, 0.83685565, 0.44609154],
        [0.81904052, 0.01898869, 0.82659522, 0.62912332, 0.01337319]],

       [[0.42495701, 0.49503909, 0.41919322, 0.48698005, 0.45675936],
        [0.33641144, 0.86985485, 0.1194013 , 0.48832484, 0.42829957],
        [0.76556338, 0.72049065, 0.15199387, 0.33596755, 0.10591494],
        [0.83090215, 0.2236324 , 0.54520479, 0.12200136, 0.25197738]],

       [[0.71720053, 0.83135443, 0.574947  , 0.29347645, 0.21054061],
        [0.93102688, 0.81060711, 0.71439401, 0.38622655, 0.35583197],
        [0.58932126, 0.71032292, 0.37930782, 0.01751352, 0.06463407],
        [0.98730597, 0.93993252, 0.72347861, 0.75346643, 0.69127034]]])

<br>np.randome.`uniform`(low, high, size)<br>
<br>*Uniform Distribution*<br>

In [75]:
u = np.random.uniform(0, 10, (3,4))
u

array([[3.84030768, 2.57302887, 8.2940192 , 7.36382704],
       [5.07600908, 6.44326615, 2.13186565, 8.95708949],
       [9.65946252, 3.17001562, 8.65552618, 3.10283707]])

<br>np.randome.`randn`(d0,d1,...dn)<br>
<br>np.random.`normal`(mean, std, size)<br>
<br>*Normal Distribution*<br>

In [15]:
sn = np.random.randn(3,4,5)
sn

array([[[ 1.17995564,  0.23752497,  0.74699552, -3.27794965,
          1.05146645],
        [ 0.54784411, -0.16482746, -0.15895319,  0.0036947 ,
          0.32513198],
        [ 1.87931182,  0.02610187, -0.47806797, -0.03486927,
          0.80573843],
        [ 0.93713812, -0.25804993, -0.06807035,  0.7393449 ,
          1.44890901]],

       [[-0.36448078, -0.19082407, -0.35987144, -0.75116573,
          0.15544115],
        [-0.04649267, -1.69770895, -0.86272208,  0.6584724 ,
          1.74152665],
        [ 1.28994106, -0.65342586, -0.41071587, -2.2856712 ,
          0.31979916],
        [-0.78403011, -0.78488007,  1.09323545,  1.73944223,
          0.68010344]],

       [[ 0.68218442, -1.01147963, -0.75885229, -0.92970771,
          0.49906729],
        [ 0.03351399,  0.39966111,  1.53421015, -0.47380534,
         -3.01207471],
        [ 0.3806479 , -0.26777363,  1.70208714, -0.41656186,
         -0.07573616],
        [ 0.89478601,  0.17981764, -0.58250127, -0.20792698,
          0

In [87]:
sn = np.random.normal(0,1,(3,4))
sn
#print(sn[:,:].mean(),sn[:,:].std())
#print(sn[0,:].mean(),sn[0,:].std())
#print(sn[1,:].mean(),sn[1,:].std())

-0.0012112646379223507 0.9996646766872029
-0.00038541043714084917 0.9996102053240553
-0.0020371188387038534 0.9997184628553867


np.random.`randint`(low, high, shape)<br>
<br>*integer random number in [low,high)*<br>

In [35]:
b = np.random.randint(100,200,(3,4))
b

array([[115, 106, 185, 122],
       [111, 112, 192, 196],
       [162, 157, 179, 142]])

<br>np.random.`shuffle`(array)<br><br>
*modify the array*

In [24]:
np.random.shuffle(b)
b # is modified

array([[111, 154, 188, 162],
       [151, 154, 177, 169],
       [133, 172, 178, 149]])

In [25]:
np.random.shuffle(b)
b # Shuffle based on "rank/column" 
    # to keep the meaning of data

array([[133, 172, 178, 149],
       [111, 154, 188, 162],
       [151, 154, 177, 169]])

<br>np.random.`permutation`(array)<br><br>
*return an array*

In [27]:
print(np.random.permutation(b))
b # does not modify

[[111 154 188 162]
 [133 172 178 149]
 [151 154 177 169]]


array([[133, 172, 178, 149],
       [111, 154, 188, 162],
       [151, 154, 177, 169]])

<br>np.random.`choice`(1D-array, size, replace, p)<br><br>
*select element at probability 'p' <br>
to return a array of 'size'<br>
'replace' is True by default -- can NOT Re-select same element*

In [68]:
c = np.random.randint(100,200,(8))
c

TypeError: randint() got an unexpected keyword argument 'replace'

In [69]:
np.random.choice(c,(3,2),True) #Replace=True : can repeatedly draw from same position

array([[118, 144],
       [177, 118],
       [163, 183]])

In [65]:
np.random.choice(c,(3,2),replace=False) #One-position can only be drawn once

array([[144, 101],
       [177, 163],
       [118, 137]])

In [71]:
np.random.choice(c,(3,2), p = c/np.sum(c))#larger number, higher chance

array([[183, 118],
       [177, 101],
       [183, 118]])

In [ ]:
# Random Functions in Numpy

import numpy as np

np.random.`seed()` <br>
<br> *Select the seed (optional)*

np.random.seed(10) #same outcome for same seed

np.random.`rand`(d0,d1,...dn)<br>
<br> *Create float in [0,1)*<br>

a = np.random.rand(3, 4, 5)
a

<br>np.randome.`uniform`(low, high, size)<br>
<br>*Uniform Distribution*<br>

u = np.random.uniform(0, 10, (3,4))
u

<br>np.randome.`randn`(d0,d1,...dn)<br>
<br>np.random.`normal`(mean, std, size)<br>
<br>*Normal Distribution*<br>

sn = np.random.randn(3,4,5)
sn

sn = np.random.normal(0,1,(3,4))
sn
#print(sn[:,:].mean(),sn[:,:].std())
#print(sn[0,:].mean(),sn[0,:].std())
#print(sn[1,:].mean(),sn[1,:].std())

np.random.`randint`(low, high, shape)<br>
<br>*integer random number in [low,high)*<br>

b = np.random.randint(100,200,(3,4))
b

<br>np.random.`shuffle`(array)<br><br>
*modify the array*

np.random.shuffle(b)
b # is modified

np.random.shuffle(b)
b # Shuffle based on "rank/column" 
    # to keep the meaning of data

<br>np.random.`permutation`(array)<br><br>
*return an array*

print(np.random.permutation(b))
b # does not modify

<br>np.random.`choice`(1D-array, size, replace, p)<br><br>
*select element at probability 'p' <br>
to return a array of 'size'<br>
'replace' is True by default -- can NOT Re-select same element*

c = np.random.randint(100,200,(8))
c

np.random.choice(c,(3,2),True) #Replace=True : can repeatedly draw from same position

np.random.choice(c,(3,2),replace=False) #One-position can only be drawn once

np.random.choice(c,(3,2), p = c/np.sum(c))#larger number, higher chance

# NumpyFiles

In [1]:
import numpy as np

## Save CSV Files

`np.savetxt`(frame,array,fmt='%.18e',delimiter=None)


In [2]:
a = np.arange(100).reshape(5,20)

In [5]:
np.savetxt('a.csv', a, fmt='%d', delimiter=',')
#the csv file has been created into working folder

In [7]:
np.savetxt('a.csv', a, fmt='%.1f', delimiter=',')
#create another file with one-decimal precision

## Read CSV Files

`np.loadtxt`(frame,dtype=np.float,delimeter=None,unpack=False)



In [10]:
b = np.loadtxt('a.csv', delimiter=',') #default float
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [35]:
b = np.loadtxt('a.csv', dtype = 'i', delimiter=',')
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]], dtype=int32)

# Multidimensional Files

In [28]:
import numpy as np

## Write to Files

a`.tofile`(frame, sep='', format='%s')

In [36]:
c = np.arange(100).reshape(5,10,2)

In [37]:
c.tofile('c.dat', sep=',', format='%d')
#create a 'CSV-like' file 

## Read from Files

np.`fromfile`(frame, dtype=float, count=-1, sep='')<br><br>
*count=-1 :read entire file<br>
sep='':read bit-format file*

In [41]:
d = np.fromfile('c.dat', dtype=np.int, sep=',')#read into one array
d.resize((5,10,2)) #recover the dimension
print(d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]
  [30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]
  [50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]
  [70 71]
  [72 73]
  [74 75]
  [76 77]
  [78 79]]

 [[80 81]
  [82 83]
  [84 85]
  [86 87]
  [88 89]
  [90 91]
  [92 93]
  [94 95]
  [96 97]
  [98 99]]]


## Advanced Save and Load 

`np.save`(fname, array) *--save to .npy*<br>
<br>
`np.savez`(fname, array) *--save to .npz(zipped)*<br>
<br>
`np.load`(fname) *--load .npy or .npz*<br>
<br>
**Dimension is Automatically Saved and Recovered!**

In [42]:
e = np.arange(100).reshape(5, 10 ,2)

In [43]:
np.save('e.npy', e)
#Dimensional info is saved in first line of the file

In [48]:
f= np.load('e.npy') #Recognize Dimension by reading first line
f

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])